sudo: required
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: G/DF6At4d4x103YfwLtUqvi+WfNm2NFNGcBgcPoh0E1awupa2EW3LhAooFCLMoPZlhD14eqKoi/bEyJ9NhXfi72NQvwYwh+uS+0bKo+NHE/TsMssjE+NrosgslbizJdzneCGTgg+awA7S4bd91/nXuKFqD1q1g4xhU5o5Y2Ah2mmKoW9nuXYQF1EWskwRI7QtuwyDsEWdDvdscEQn6MdSJse9pG4T1GIu/rcvjpZXdFenCkr+zET93NhPExWS9zHNFCtln1Jjv89G/SUHIF9ixS1ImlU066YlysTRp/OwjuJ2uJlxIpAbzY+HSg+El4S3lHomJ9bgACWSyD36cJeiOrIVHtAf+//lWr62pTS/tZCigNN2dbNDFk7z+jXFB+eSMJHXtwHNeCy7n4bXW5M0/dXx0XDO34zrtXmEreanduzehrZOZve8wRx4lTU+FeTqZpc5rYhsXIRrhJd+iC4NQ8OwNhgrm93tya3Lt3K/3DbqphrY9e03AozWCkNWMpjjzY7aBgdBHV2zCcWZkK2VScLOzILj5SyqPdsSE6Cr21nXVbzK9xFQ5Uk1xO5xkb16Dx2uB91ETVD2fxYSRBuDlRtG/Np6xXZsO67Q+xv7eJmIJ9+upv2einyq7Hoc3zeb6Cw7yssdv5D4A7ExRKtvtM1qMxNMmoX+XHSEqIiDO0=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_c1188d46b285_key -iv $encrypted_c1188d46b285_iv
  -in service-account.json.enc -out service-account.json -d
- curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project my-jenkins-259119
- gcloud config set compute/zone us-west1-a
- gcloud container clusters get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kkweon/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true kkweon/react-test npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
