sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_c1188d46b285_key -iv $encrypted_c1188d46b285_iv
  -in service-account.json.enc -out service-account.json -d
- curl https://sdk.cloud.google.com | bash /dev/stdin --disable-prompts;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project my-jenkins-259119
- gcloud config set compute/zone us-west1-a
- gcloud container clusters get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t kkweon/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true kkweon/docker-react npm run test
env:
  global:
    secure: uYcj3lfhWjOvIaXayq7WXbkraor/EqYjR6uGLJa8YpSN3+mO+To2Ob92kdSH+vD6txEEOdTI6N7dMMbEo4ulAREqrUmieD9rTIyG5X7To8Fss3IBhYAJgE0PVSQiO75WCI2+x2QrTzrTWUnhq4HEzEdYL+aTzVpW5wQTWrLonQ5ihqP3VOson1JaRkHg+6tZlyDYuMnjymEUusmiPdYlsCxStTOCltXqIALNywc01iZwN1Id+BHDUkw0I71bsHSAOaUHk8G/5f46vByQTSkhapzQ6tdOgsz+81Sjpv89pXCTO6XG0fVPs3n5JLz3HAgN/jgkmPOi32NPVIkWab1Jod3krPB50jcYnpq/YsDMbCIrALvGVkJ2v5Rd+o3tj+Tp0weYOjpi/K6BipBm0LQTZU0gJM3raAx8tAo1ugyK6Eu08B7vE5IFYRqNQf1sz6jnCAgOsk244NpROuQnTxlR+/MVZEnE4AxLcRCQOygwNSA663fpg7GolWZWVE+B3UFKA9FsN1QDpxZyxzIIN3CMsGTakRiHc3mH/gK5kNVfWeQHyAtIU657aHVx1/xmUTuf4UZyXNQVm5zMpoFo/KFqutPIe80xV+Ndi77wd47DG+szaE+hwQvkvvWHEpb2F3ggyJMB0gmNZqJF0OtL8oixif9bmjAFBb6PuX6MvRmiTWs=
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
