apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
        - image: richardchesterwood/k8s-fleetman-api-gateway:performance
          name: k8s-fleetman-api-gateway
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
