apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleetman-mongo
  name: fleetman-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongo
  template:
    metadata:
      labels:
        app: fleetman-mongo
    spec:
      containers:
      - image: mongo:3.6
        name: mongo
        ports:
          - containerPort: 27017
        envFrom:
          - secretRef:
              name: fleetman-mongo-secret
