apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-position-tracker:release1
        name: k8s-fleetman-position-tracker
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

