apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kkweon-dev-tls
spec:
  secretName: kkweon-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kkweon.dev
  dnsNames:
    - kkweon.dev
    - www.kkweon.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kkweon.dev
          - www.kkweon.dev
