apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: "dbport"
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: "adminport"
    port: 33060
    protocol: TCP
    targetPort: 33060
  selector:
    app: mysql
  type: ClusterIP
